name: Run AQI Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use a compatible Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Ensure dependencies are installed

      - name: Run AQI Scraper
        run: python aqi_scraper.py  # Run your scraper script

      - name: Configure Git
        run: |
          git config --global user.email "imkarthik018@gmail.com"
          git config --global user.name "itzkarthik01"

      - name: Push changes if any
        run: |
          git add aqi_data.csv
          git commit -m "Updated AQI data" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/itzkarthik01/aqi-scraper.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
